name: Terraform plan CI/CD

on:
  push:
    branches:
      - 'dev-yuji-home'
    paths:
      - 'modules/**'  # Trigger on changes to the shared module
      - 'prod/**'     # Trigger on changes to prod environments

jobs:
  get-networks:
    name: 'Get Networks'
    runs-on: ubuntu-latest
    outputs:
      networks: ${{ steps.set-networks.outputs.networks }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get all networks
      id: set-networks
      run: |
        networks=$(ls -d prod/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
        echo "networks=$networks" >> $GITHUB_OUTPUT
  
  terraform:
    name: 'Terraform'
    needs: get-networks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: ${{ fromJson(needs.get-networks.outputs.networks) }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Specify your Terraform version

    - name: Terraform Init
      run: |
        cd prod/${{ matrix.network }}
        terraform init

    - name: Terraform Plan
      run: |
        cd prod/${{ matrix.network }}
        terraform plan -out=tfplan
